- model: GNN
  operations:
    train_gcn:
      main: main
      flags:
        epochs: 200
        learning_rate: 0.001
        hidden_channels: 16
        out_channels: 32
        model: 'shallow'
        target: 'rating_sleep'
        shuffle: False

      requires:
        #- file: data/event_tag_graph.dat
        - file: event_tag_graph.dat
      output-scalars: 
        - step: 'epoch: (\value)'
        - loss: 'loss: (\value)'
        - accuracy: 'accuracy: (\value)'
    train_gat:
      main: main
      flags:
        epochs: 200
        learning_rate: 0.001
        hidden_channels: 16
        out_channels: 32
        model: 'GAT'
        target: 'rating_sleep'
        shuffle: False
        dropout: 0.2
        heads: 5

      requires:
        #- file: data/event_tag_graph.dat
        - file: event_tag_graph.dat
      output-scalars: 
        - step: 'epoch: (\value)'
        - loss: 'loss: (\value)'
        - accuracy: 'accuracy: (\value)'
